# This is a config for E2B sandbox template.
# You can use template ID (11gyggj6bxpx0hfabx8k) or template name (vibe-nextjs-test-murtaza-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-murtaza-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-murtaza-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-murtaza-2')

team_id = "a7148b17-eb20-4af4-80bf-61ac045f0c88"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-murtaza-2"
template_id = "11gyggj6bxpx0hfabx8k"
